services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
      network: host
    container_name: caddyui-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    environment:
      CADDY_ADMIN: 0.0.0.0:2019
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
    command: ["sh", "-c", "mkdir -p /config/caddy && [ -f /config/caddy/autosave.json ] || echo '{}' > /config/caddy/autosave.json && exec caddy run --config /config/caddy/autosave.json --resume --adapter json"]
    networks:
      - caddyui
  
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - caddyui


volumes:
  caddy_data:
  caddy_config:

networks:
  caddyui:
    driver: bridge